"""add contact tags for campaign segments

Revision ID: 702f63144e46
Revises: 7f73b1434cf1
Create Date: 2026-09-09 01:38:09.464225
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '702f63144e46'
down_revision = '7f73b1434cf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'tags')
    # ### end Alembic commands ###
