"""add email campaign analytics tables

Revision ID: 7f73b1434cf1
Revises: d4a1c9e7b2f8
Create Date: 2026-09-09 01:31:34.790738
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7f73b1434cf1'
down_revision = 'd4a1c9e7b2f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('consent_basis', sa.Enum('express', 'implied', 'contract', 'signup', 'demo_request', 'unknown', name='consent_basis'), nullable=False),
    sa.Column('consent_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_note', sa.Text(), nullable=False),
    sa.Column('tracking_consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'unsubscribed', 'bounced', 'retired', name='contact_status'), nullable=False),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.Column('last_engaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_ignored', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_index(op.f('ix_contacts_status'), 'contacts', ['status'], unique=False)
    op.create_table('sender_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('smtp', 'mailgun', name='sender_provider'), nullable=False),
    sa.Column('mailgun_domain', sa.String(length=255), nullable=False),
    sa.Column('encrypted_api_key', sa.String(length=500), nullable=True),
    sa.Column('encrypted_webhook_secret', sa.String(length=500), nullable=True),
    sa.Column('mailgun_region', sa.Enum('us', 'eu', name='mailgun_region'), nullable=False),
    sa.Column('from_name', sa.String(length=200), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('reply_domain', sa.String(length=255), nullable=False),
    sa.Column('tracking_base_url', sa.String(length=500), nullable=False),
    sa.Column('postal_address', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sender_settings'))
    )
    op.create_table('suppressions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.Enum('unsubscribed', 'complained', 'hard_bounced', 'manual', name='suppression_reason'), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppressions'))
    )
    op.create_index(op.f('ix_suppressions_email'), 'suppressions', ['email'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('preheader', sa.String(length=300), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'sending', 'sent', 'failed', name='campaign_status'), nullable=False),
    sa.Column('segment', sa.String(length=100), nullable=False),
    sa.Column('variant_b_subject', sa.String(length=500), nullable=False),
    sa.Column('holdout_percent', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_campaigns_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('campaign_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('variant', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=500), nullable=False),
    sa.Column('pixel_embedded', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('send_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_messages_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_campaign_messages_contact_id_contacts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_messages'))
    )
    op.create_index(op.f('ix_campaign_messages_campaign_id'), 'campaign_messages', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_messages_contact_id'), 'campaign_messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_campaign_messages_provider_message_id'), 'campaign_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_campaign_messages_token'), 'campaign_messages', ['token'], unique=True)
    op.create_table('email_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_message_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('type', sa.Enum('accepted', 'delivered', 'soft_bounced', 'hard_bounced', 'complained', 'unsubscribed', 'opened', 'clicked', 'page_confirmed', 'replied', 'auto_replied', name='email_event_type'), nullable=False),
    sa.Column('tier', sa.Enum('exact', 'verified', 'inferred', 'derived', name='email_event_tier'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('classification', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['campaign_message_id'], ['campaign_messages.id'], name=op.f('fk_email_events_campaign_message_id_campaign_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_events')),
    sa.UniqueConstraint('dedupe_key', name='uq_email_events_dedupe_key')
    )
    op.create_index(op.f('ix_email_events_campaign_message_id'), 'email_events', ['campaign_message_id'], unique=False)
    op.create_index(op.f('ix_email_events_email'), 'email_events', ['email'], unique=False)
    op.create_index(op.f('ix_email_events_occurred_at'), 'email_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_email_events_type'), 'email_events', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_events_type'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_occurred_at'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_email'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_campaign_message_id'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_campaign_messages_token'), table_name='campaign_messages')
    op.drop_index(op.f('ix_campaign_messages_provider_message_id'), table_name='campaign_messages')
    op.drop_index(op.f('ix_campaign_messages_contact_id'), table_name='campaign_messages')
    op.drop_index(op.f('ix_campaign_messages_campaign_id'), table_name='campaign_messages')
    op.drop_table('campaign_messages')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_suppressions_email'), table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_table('sender_settings')
    op.drop_index(op.f('ix_contacts_status'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###

    # NOT auto-generated, and required. Postgres keeps an ENUM type after the
    # table that used it is dropped: `sa.Enum` creates the type as a side
    # effect of create_table, but drop_table does not remove it. Without this
    # loop a downgrade leaves eight orphaned types behind and the NEXT upgrade
    # dies on `type "consent_basis" already exists`, which reads like a broken
    # migration rather than a leftover. Found by round-tripping this migration
    # down and back up before it shipped.
    for enum_name in (
        "email_event_tier",
        "email_event_type",
        "campaign_status",
        "suppression_reason",
        "sender_provider",
        "mailgun_region",
        "contact_status",
        "consent_basis",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
