"""add trust tables

Revision ID: a132dbcacc3b
Revises: f63fe229a69a
Create Date: 2026-09-09 15:32:07.651793
"""
from alembic import op
import sqlalchemy as sa


revision = 'a132dbcacc3b'
down_revision = 'f63fe229a69a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocklist_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('blocklist', sa.String(length=255), nullable=False),
    sa.Column('listed', sa.Boolean(), nullable=False),
    sa.Column('response', sa.String(length=100), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocklist_results'))
    )
    op.create_index(op.f('ix_blocklist_results_checked_at'), 'blocklist_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_blocklist_results_target'), 'blocklist_results', ['target'], unique=False)
    op.create_table('dmarc_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('report_id', sa.String(length=255), nullable=False),
    sa.Column('date_begin', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('policy_domain', sa.String(length=255), nullable=False),
    sa.Column('header_from', sa.String(length=255), nullable=False),
    sa.Column('policy_p', sa.String(length=20), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('disposition', sa.String(length=20), nullable=False),
    sa.Column('dkim_aligned', sa.Boolean(), nullable=False),
    sa.Column('spf_aligned', sa.Boolean(), nullable=False),
    sa.Column('dkim_domain', sa.String(length=255), nullable=False),
    sa.Column('spf_domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dmarc_records')),
    sa.UniqueConstraint('report_id', 'source_ip', 'header_from', name='uq_dmarc_records_report_id')
    )
    op.create_index(op.f('ix_dmarc_records_date_begin'), 'dmarc_records', ['date_begin'], unique=False)
    op.create_index(op.f('ix_dmarc_records_header_from'), 'dmarc_records', ['header_from'], unique=False)
    op.create_index(op.f('ix_dmarc_records_report_id'), 'dmarc_records', ['report_id'], unique=False)
    op.create_index(op.f('ix_dmarc_records_source_ip'), 'dmarc_records', ['source_ip'], unique=False)
    op.create_table('seed_inboxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('imap_username', sa.String(length=320), nullable=False),
    sa.Column('encrypted_password', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seed_inboxes')),
    sa.UniqueConstraint('email', name=op.f('uq_seed_inboxes_email'))
    )
    op.create_table('seed_placements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('seed_inbox_id', sa.UUID(), nullable=False),
    sa.Column('placement', sa.Enum('inbox', 'spam', 'promotions', 'missing', 'error', name='seed_placement'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seed_placements')),
    sa.UniqueConstraint('campaign_id', 'seed_inbox_id', name='uq_seed_placements_campaign_id')
    )
    op.create_index(op.f('ix_seed_placements_campaign_id'), 'seed_placements', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_seed_placements_seed_inbox_id'), 'seed_placements', ['seed_inbox_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seed_placements_seed_inbox_id'), table_name='seed_placements')
    op.drop_index(op.f('ix_seed_placements_campaign_id'), table_name='seed_placements')
    op.drop_table('seed_placements')
    op.drop_table('seed_inboxes')
    op.drop_index(op.f('ix_dmarc_records_source_ip'), table_name='dmarc_records')
    op.drop_index(op.f('ix_dmarc_records_report_id'), table_name='dmarc_records')
    op.drop_index(op.f('ix_dmarc_records_header_from'), table_name='dmarc_records')
    op.drop_index(op.f('ix_dmarc_records_date_begin'), table_name='dmarc_records')
    op.drop_table('dmarc_records')
    op.drop_index(op.f('ix_blocklist_results_target'), table_name='blocklist_results')
    op.drop_index(op.f('ix_blocklist_results_checked_at'), table_name='blocklist_results')
    op.drop_table('blocklist_results')
    # ### end Alembic commands ###

    # Not auto-generated, and required — the same omission that broke the
    # analytics migration's downgrade. `sa.Enum` creates the Postgres type as
    # a side effect of create_table, and drop_table does not remove it, so a
    # downgrade leaves it orphaned and the next upgrade dies on
    # `type "seed_placement" already exists`.
    op.execute("DROP TYPE IF EXISTS seed_placement")
