"""add converted event type for product attribution

Written by hand, not autogenerated: Alembic's autogenerate compares tables and
columns and does not notice a new value on an existing enum, so this would
have silently produced an empty migration and then failed at runtime the first
time the product reported a conversion.

Revision ID: f63fe229a69a
Revises: fdd908ed97a5
Create Date: 2026-09-09 15:07:55.650715
"""
from alembic import op

revision = 'f63fe229a69a'
down_revision = 'fdd908ed97a5'
branch_labels = None
depends_on = None

NEW_VALUE = "converted"
ENUM_NAME = "email_event_type"


def upgrade() -> None:
    # IF NOT EXISTS makes it safe to re-run, which matters because the dev
    # server applies migrations on every service restart.
    op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE IF NOT EXISTS '{NEW_VALUE}'")


def downgrade() -> None:
    """Deliberately a no-op.

    Postgres has no DROP VALUE. Removing one means recreating the type,
    rewriting every column that uses it and re-creating the indexes and
    defaults — a large, risky operation to undo one unused label. Any row
    actually carrying the value would have to be deleted or rewritten first,
    which would silently destroy attribution data.

    Leaving the value in place costs nothing: an enum member no code emits is
    inert. The alternative is a downgrade path that is far more dangerous than
    the thing it reverses.
    """
