"""add campaign links for click tracking

Revision ID: fdd908ed97a5
Revises: 702f63144e46
Create Date: 2026-09-09 14:02:27.294985
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'fdd908ed97a5'
down_revision = '702f63144e46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'links')
    # ### end Alembic commands ###
